// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savdonoma.Data;

#nullable disable

namespace Savdonoma.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006133551_createdAtToCategory")]
    partial class createdAtToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("Savdonoma.Core.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SYS_CATEGORY", (string)null);
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("BARCODE")
                        .HasColumnOrder(5);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CATEGORY_ID")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(6);

                    b.Property<string>("NameSearch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NAME_SEARCH")
                        .HasColumnOrder(7);

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("PRICE")
                        .HasColumnOrder(2);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UNIT")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("NameSearch");

                    b.ToTable("SYS_PRODUCT", (string)null);
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("CancelReason")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CANCEL_REASON")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CANCELLED_AT")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(9);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NUMBER")
                        .HasColumnOrder(1);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAYMENT_METHOD")
                        .HasColumnOrder(3);

                    b.Property<int>("SaleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("TOTAL_AMOUNT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.ToTable("SYS_SALES", (string)null);
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(8);

                    b.Property<long>("LineTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("LINE_TOTAL")
                        .HasColumnOrder(6);

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PRODUCT_NAME")
                        .HasColumnOrder(5);

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTITY")
                        .HasColumnOrder(3);

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("SALE_ID")
                        .HasColumnOrder(1);

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("TOTAL_AMOUNT")
                        .HasColumnOrder(7);

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("UNIT_PRICE")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SYS_SALE_ITEMS", (string)null);
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.Product", b =>
                {
                    b.HasOne("Savdonoma.Core.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.SaleItem", b =>
                {
                    b.HasOne("Savdonoma.Core.Entity.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Savdonoma.Core.Entity.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.Product", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Savdonoma.Core.Entity.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
